const SAVE_KEY="ashfall-v2";
const canvas=document.getElementById("worldCanvas"),ctx=canvas.getContext("2d"),viewport=document.getElementById("viewport");

const DATA={
areas:{
  greywood:{name:"Greywood",sub:"Old Forest",color:"#253128",spawn:[700,520]},
  cinder:{name:"Cinder Road",sub:"The Burnt Highway",color:"#362b25",spawn:[420,420]},
  salt:{name:"Saltmarsh",sub:"Drowned Country",color:"#202f2c",spawn:[820,560]},
  high:{name:"Highreach",sub:"Mountain Kingdom",color:"#2d3037",spawn:[920,260]},
  ashen:{name:"Ashen Veil",sub:"Ruined Heart",color:"#312624",spawn:[520,220]},
  below:{name:"Below",sub:"Unknown",color:"#13131a",spawn:[720,500]}
},
items:[
{id:"sword",name:"Rusty Sword",type:"Weapon",rarity:"common",slot:"main",power:5,desc:"A battered blade. Honest, if ugly."},
{id:"buckler",name:"Oak Buckler",type:"Shield",rarity:"common",slot:"off",armor:4,desc:"Cheap wood with a surprisingly solid rim."},
{id:"cloak",name:"Wanderer's Cloak",type:"Armor",rarity:"common",slot:"chest",armor:3,desc:"Smells of rain and old roads."},
{id:"bone",name:"Bone Knife",type:"Weapon",rarity:"rare",slot:"main",power:10,crit:5,desc:"Carved from something that wanted to stay alive."},
{id:"emberring",name:"Ember Ring",type:"Relic",rarity:"rare",slot:"ring",mp:8,magic:4,desc:"Warm even when it should be cold."},
{id:"coin",name:"Beggar's Coin",type:"Relic",rarity:"epic",slot:"ring",luck:12,desc:"It always lands on the side you did not choose."},
{id:"halberd",name:"Ashen Halberd",type:"Weapon",rarity:"epic",slot:"main",power:17,desc:"Its edge smolders when blood is near."},
{id:"needle",name:"Black Needle",type:"Weapon",rarity:"legendary",slot:"main",power:28,crit:18,desc:"A weapon found in a dead thief's hand."}],
skills:[
{id:"strike",name:"Rending Strike",kind:"Combat",lvl:1,cost:0,desc:"A brutal weapon strike."},
{id:"guard",name:"Iron Guard",kind:"Defense",lvl:1,cost:6,desc:"Brace and reduce the next incoming hit."},
{id:"focus",name:"Deep Focus",kind:"Arcane",lvl:2,cost:8,desc:"Recover MP and sharpen your next attacks."},
{id:"ember",name:"Embercraft",kind:"Elemental",lvl:3,cost:10,desc:"Hurl a burning fragment of your will."},
{id:"bloodstep",name:"Bloodstep",kind:"Forbidden",lvl:4,cost:12,desc:"Trade 10 HP for a guaranteed critical."},
{id:"veil",name:"Veilwalking",kind:"Shadow",lvl:6,cost:18,desc:"Step half a second outside the world."}],
classes:[
{id:"unbound",name:"Unbound",rarity:"common",desc:"No oath. No class. No expectations.",req:"Your story begins without a class."},
{id:"sellsword",name:"Sellsword",rarity:"common",desc:"A practical fighter who learned to survive.",req:"Reach level 3 after taking the Red Coin contract."},
{id:"warden",name:"Warden",rarity:"rare",desc:"A protector without a kingdom.",req:"Refuse the Road Warden's offer and learn Guard."},
{id:"hex",name:"Hexblade",rarity:"epic",desc:"Steel has learned the language of curses.",req:"Learn Embercraft while carrying the Ember Ring."},
{id:"blood",name:"Blood Knight",rarity:"legendary",desc:"Pain is a resource. Fear is a lie.",req:"A hidden trial involving the Road Warden."},
{id:"fool",name:"Fool",rarity:"rare",desc:"Everyone thinks you are joking. That is useful.",req:"Fail three class trials while carrying the Beggar's Coin."},
{id:"void",name:"Void-Touched",rarity:"mythic",desc:"The world noticed you looking beneath it.",req:"Discover the path Below."}],
enemies:{
wolf:{id:"wolf",name:"Grey Wolf",level:1,hp:42,power:9,armor:2,xp:35,gold:12,loot:"bone"},
bandit:{id:"bandit",name:"Cinder Bandit",level:2,hp:66,power:12,armor:4,xp:52,gold:26,loot:"halberd"},
bog:{id:"bog",name:"Bogling",level:3,hp:86,power:14,armor:5,xp:70,gold:34,loot:"emberring"},
warden:{id:"warden",name:"The Road Warden",level:5,hp:190,power:23,armor:8,xp:180,gold:120,loot:"needle"}
}
};

const START={player:{name:"Ashborn",level:1,xp:0,gold:40,hp:100,maxHp:100,mp:24,maxMp:24,str:7,dex:6,int:5,vit:6,luck:1,armor:0,crit:4,magic:0,classId:"unbound",skills:["strike"],inv:["sword","buckler","cloak"],eq:{main:"sword",off:"buckler",chest:"cloak",ring:null},flags:{red:false,bribe:false,firstBoss:false,blood:false,fool:0,secret:false},area:"greywood",x:700,y:520},quest:{stage:0,title:"A Door in the Fog",text:"Find the old waystone beyond Greywood. Someone has left a mark there that looks almost like your name."},known:["greywood","cinder","salt"],dead:[],log:["The road gives way to trees.","The forest is quiet in a way that does not feel peaceful."]};

let S=load(),keys={},nearEntity=null,combat=null,dialogue=false,cam={x:0,y:0};
const item=id=>DATA.items.find(x=>x.id===id),skill=id=>DATA.skills.find(x=>x.id===id),cls=id=>DATA.classes.find(x=>x.id===id),area=id=>DATA.areas[id];
const WORLD={w:1800,h:1200};
const trees=[];const rocks=[];const grass=[];
function seedWorld(){let r=mulberry(7331);for(let i=0;i<170;i++)trees.push({x:80+Math.random()*1640,y:100+Math.random()*980,s:.75+Math.random()*1.25});for(let i=0;i<75;i++)rocks.push({x:50+Math.random()*1700,y:80+Math.random()*1040,s:.6+Math.random()*1.1});for(let i=0;i<700;i++)grass.push({x:Math.random()*1800,y:Math.random()*1200,a:.25+Math.random()*.55})}
function mulberry(a){return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(S))}
function load(){try{let v=localStorage.getItem(SAVE_KEY);if(v)return JSON.parse(v)}catch{}return structuredClone(START)}
function log(t){S.log.unshift(t);S.log=S.log.slice(0,40);document.getElementById("worldLog").innerHTML=S.log.slice(0,10).map(x=>"<div class='log-entry'>"+x+"</div>").join("");save()}
function toast(t){let e=document.getElementById("toast");e.textContent=t;e.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove("show"),2200)}
function pop(t,type=""){let e=document.getElementById("floatingText");e.textContent=t;e.className="floating-text show "+type;setTimeout(()=>e.className="floating-text",1000)}
function xpNeed(){return 100+(S.player.level-1)*65}
function attackPower(){let w=item(S.player.eq.main);return(w?.power||1)+S.player.str*1.45+S.player.dex*.35}
function armor(){let n=S.player.armor;for(let id of Object.values(S.player.eq)){let i=item(id);if(i?.armor)n+=i.armor}return n}
function crit(){let n=S.player.crit;for(let id of Object.values(S.player.eq)){let i=item(id);if(i?.crit)n+=i.crit}return n}
function magic(){let n=S.player.magic;for(let id of Object.values(S.player.eq)){let i=item(id);if(i?.magic)n+=i.magic}return n}
function addXP(n){S.player.xp+=n;while(S.player.xp>=xpNeed()){S.player.xp-=xpNeed();S.player.level++;S.player.maxHp+=14;S.player.maxMp+=4;S.player.hp=S.player.maxHp;S.player.mp=S.player.maxMp;S.player.str++;S.player.vit++;if(S.player.level%2===0)S.player.dex++;if(S.player.level%3===0)S.player.int++;log("<b>LEVEL UP</b> You are now level "+S.player.level+".");toast("LEVEL "+S.player.level);discoverSkill()}evaluateClasses()}
function discoverSkill(){let c=DATA.skills.filter(s=>s.lvl<=S.player.level&&!S.player.skills.includes(s.id));if(c.length&&Math.random()<.75){let s=c[Math.floor(Math.random()*c.length)];S.player.skills.push(s.id);log("<b>SKILL DISCOVERED</b> "+s.name+" — "+s.desc);toast("Skill discovered: "+s.name)}}
function evaluateClasses(){let p=S.player;if(p.level>=3&&p.flags.red&&p.classId==="unbound")unlockClass("sellsword");if(p.flags.bribe&&p.skills.includes("guard")&&p.classId==="unbound")unlockClass("warden");if(p.skills.includes("ember")&&p.inv.includes("emberring")&&p.classId==="unbound")unlockClass("hex");if(p.flags.secret&&p.classId!=="void")unlockClass("void");if(p.flags.fool>=3&&p.inv.includes("coin")&&p.classId==="unbound")unlockClass("fool")}
function unlockClass(id){let c=cls(id);S.player.classId=id;log("<b>CLASS DISCOVERED</b> "+c.name+" ["+c.rarity.toUpperCase()+"] — "+c.desc);toast("CLASS DISCOVERED — "+c.name);renderUI()}
function movement(dt){if(combat||dialogue)return;let dx=(keys.d?1:0)-(keys.a?1:0),dy=(keys.s?1:0)-(keys.w?1:0);if(dx||dy){let len=Math.hypot(dx,dy);dx/=len;dy/=len;let sp=210;S.player.x=clamp(S.player.x+dx*sp*dt,35,WORLD.w-35);S.player.y=clamp(S.player.y+dy*sp*dt,55,WORLD.h-45)}}
function collides(x,y){return false}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight,dpr=devicePixelRatio||1;if(canvas.width!==w*dpr||canvas.height!==h*dpr){canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}cam.x=clamp(S.player.x-w/2,0,WORLD.w-w);cam.y=clamp(S.player.y-h/2,0,WORLD.h-h);ctx.clearRect(0,0,w,h);drawTerrain(w,h);drawWorldObjects();drawPlayer();drawAtmosphere(w,h);findNear()}
function drawTerrain(w,h){let base=area(S.player.area);ctx.fillStyle=base?.color||"#28302a";ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(-cam.x,-cam.y);
ctx.fillStyle="#303a31";ctx.fillRect(0,0,WORLD.w,WORLD.h);
for(const g of grass){ctx.globalAlpha=g.a;ctx.fillStyle="#4a5948";ctx.fillRect(g.x,g.y,2,5);ctx.fillRect(g.x+3,g.y+1,1.5,4)}ctx.globalAlpha=1;
if(S.player.area==="greywood"){drawPath("#554638",[0,530,450,500,860,545,1220,610,1800,560]);drawLake(1450,220,250,140);for(const t of trees)drawTree(t.x,t.y,t.s);for(const r of rocks)drawRock(r.x,r.y,r.s);drawHouse(355,450,1.1);drawHouse(1180,650,.9);drawRuin(870,250,1.15);drawWaystone(930,405)}
if(S.player.area==="cinder"){drawPath("#6d4a35",[0,580,350,560,760,575,1110,530,1800,540]);drawBurntForest();drawCamp(940,455);drawWagon(510,510);drawSign(735,490)}
if(S.player.area==="salt"){drawMarsh();drawPath("#534638",[0,650,500,610,940,640,1450,590,1800,620]);drawShrine(1080,410);drawDeadTrees();drawWaterPatches()}
if(S.player.area==="high"){drawMountains();drawFortress(1120,310);drawCliffRoad()}
if(S.player.area==="ashen"){drawAshenRuins();drawObelisk(900,420)}
if(S.player.area==="below"){drawBelow()}
ctx.restore()}
function drawPath(c,pts){ctx.strokeStyle=c;ctx.lineWidth=70;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(pts[0],pts[1]);for(let i=2;i<pts.length;i+=2)ctx.lineTo(pts[i],pts[i+1]);ctx.stroke();ctx.strokeStyle="#735b42";ctx.lineWidth=58;ctx.beginPath();ctx.moveTo(pts[0],pts[1]-2);for(let i=2;i<pts.length;i+=2)ctx.lineTo(pts[i],pts[i+1]-2);ctx.stroke();ctx.lineWidth=1}
function drawTree(x,y,s=1){ctx.save();ctx.translate(x,y);ctx.fillStyle="#2a1f18";ctx.fillRect(-8*s,-2*s,16*s,48*s);ctx.fillStyle="#15261a";for(const [dx,dy,r] of [[-18,0,28],[13,-8,31],[0,-25,34],[-4,14,29]]){ctx.beginPath();ctx.arc(dx*s,dy*s,r*s,0,7);ctx.fill()}ctx.fillStyle="#254129";ctx.beginPath();ctx.arc(7*s,-30*s,22*s,0,7);ctx.fill();ctx.restore()}
function drawRock(x,y,s){ctx.save();ctx.translate(x,y);ctx.fillStyle="#3b4540";ctx.beginPath();ctx.moveTo(-17*s,10*s);ctx.lineTo(-9*s,-12*s);ctx.lineTo(7*s,-18*s);ctx.lineTo(18*s,3*s);ctx.lineTo(7*s,16*s);ctx.closePath();ctx.fill();ctx.strokeStyle="#647066";ctx.stroke();ctx.restore()}
function drawHouse(x,y,s){ctx.save();ctx.translate(x,y);ctx.fillStyle="#6a4b32";ctx.fillRect(-55*s,-25*s,110*s,80*s);ctx.fillStyle="#9a6d42";ctx.beginPath();ctx.moveTo(-70*s,-25*s);ctx.lineTo(0,-70*s);ctx.lineTo(70*s,-25*s);ctx.closePath();ctx.fill();ctx.fillStyle="#1a1410";ctx.fillRect(-14*s,18*s,28*s,37*s);ctx.fillStyle="#d5a866";ctx.fillRect(26*s,0,12*s,14*s);ctx.restore()}
function drawRuin(x,y,s){ctx.save();ctx.translate(x,y);ctx.fillStyle="#5b5148";ctx.fillRect(-75*s,-10*s,25*s,130*s);ctx.fillRect(-18*s,-45*s,32*s,165*s);ctx.fillRect(42*s,-25*s,25*s,145*s);ctx.fillStyle="#88745c";ctx.beginPath();ctx.moveTo(-86*s,-44*s);ctx.lineTo(-6*s,-76*s);ctx.lineTo(80*s,-42*s);ctx.lineTo(72*s,-20*s);ctx.lineTo(-80*s,-21*s);ctx.closePath();ctx.fill();ctx.restore()}
function drawWaystone(x,y){ctx.save();ctx.translate(x,y);ctx.fillStyle="#6d655b";ctx.beginPath();ctx.moveTo(-28,32);ctx.lineTo(-21,-20);ctx.lineTo(0,-55);ctx.lineTo(22,-20);ctx.lineTo(28,32);ctx.closePath();ctx.fill();ctx.strokeStyle="#c2a46e";ctx.stroke();ctx.fillStyle="#c7a869";ctx.fillRect(-3,-22,6,28);ctx.restore()}
function drawLake(x,y,rx,ry){ctx.fillStyle="#1f3b43";ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,7);ctx.fill();ctx.strokeStyle="#5e8990";ctx.stroke();for(let i=0;i<7;i++){ctx.strokeStyle="#40636b";ctx.beginPath();ctx.ellipse(x-rx*.5+i*50,y-15+i*5,55,8,0,0,7);ctx.stroke()}}
function drawCamp(x,y){ctx.fillStyle="#4b3828";ctx.beginPath();ctx.arc(x,y,58,0,7);ctx.fill();ctx.fillStyle="#d28c46";ctx.beginPath();ctx.arc(x,y,12,0,7);ctx.fill();ctx.fillStyle="#5c4129";ctx.fillRect(x-110,y-60,38,25);ctx.fillRect(x+70,y-50,34,24)}
function drawWagon(x,y){ctx.fillStyle="#68472e";ctx.fillRect(x-45,y-35,90,45);ctx.strokeStyle="#2c2019";ctx.lineWidth=10;ctx.beginPath();ctx.arc(x-30,y+15,18,0,7);ctx.arc(x+31,y+15,18,0,7);ctx.stroke();ctx.lineWidth=1}
function drawSign(x,y){ctx.fillStyle="#533926";ctx.fillRect(x-4,y-55,8,70);ctx.fillStyle="#8a673e";ctx.fillRect(x-55,y-70,110,35);ctx.fillStyle="#222";ctx.font="11px serif";ctx.fillText("CINDER",x-28,y-48)}
function drawBurntForest(){for(let i=0;i<45;i++){let x=80+(i*137)%1650,y=150+(i*83)%750;ctx.fillStyle="#221b17";ctx.fillRect(x,y,11,72);ctx.fillStyle="#35251e";ctx.beginPath();ctx.arc(x+6,y,25,0,7);ctx.fill()}}
function drawMarsh(){ctx.fillStyle="#1f302b";ctx.fillRect(0,0,WORLD.w,WORLD.h);for(let i=0;i<13;i++){let x=90+i*142,y=180+(i%4)*170;ctx.fillStyle="#28443b";ctx.beginPath();ctx.ellipse(x,y,130,75,0,0,7);ctx.fill()}}
function drawDeadTrees(){for(let i=0;i<27;i++){let x=120+i*63,y=140+(i*47)%800;ctx.fillStyle="#30271f";ctx.fillRect(x,y,9,70);ctx.fillRect(x-18,y+20,34,7)}}
function drawWaterPatches(){for(let i=0;i<8;i++){let x=160+i*170,y=430+(i%3)*130;ctx.fillStyle="#1d4449";ctx.beginPath();ctx.ellipse(x,y,70,28,0,0,7);ctx.fill()}}
function drawShrine(x,y){ctx.fillStyle="#6a6257";ctx.fillRect(x-9,y-80,18,140);ctx.fillStyle="#9c8968";ctx.beginPath();ctx.moveTo(x-28,y-80);ctx.lineTo(x,y-120);ctx.lineTo(x+28,y-80);ctx.closePath();ctx.fill();ctx.strokeStyle="#c2a46e";ctx.stroke()}
function drawMountains(){for(let i=0;i<9;i++){let x=i*230;ctx.fillStyle=i%2?"#3b4147":"#323940";ctx.beginPath();ctx.moveTo(x,780);ctx.lineTo(x+115,160+(i%3)*50);ctx.lineTo(x+235,780);ctx.closePath();ctx.fill()}ctx.fillStyle="#7b8086";for(let i=0;i<8;i++)ctx.fillRect(150+i*210,460+(i%2)*70,90,10)}
function drawFortress(x,y){ctx.fillStyle="#5f6263";ctx.fillRect(x-160,y-95,320,210);ctx.fillStyle="#73706b";ctx.fillRect(x-185,y-140,60,255);ctx.fillRect(x+125,y-140,60,255);ctx.fillStyle="#272a2a";ctx.fillRect(x-25,y+40,50,75);ctx.fillStyle="#9a8a6c";ctx.fillRect(x-12,y-125,24,45)}
function drawCliffRoad(){ctx.strokeStyle="#68553e";ctx.lineWidth=65;ctx.beginPath();ctx.moveTo(80,940);ctx.bezierCurveTo(450,820,500,420,1060,330);ctx.stroke();ctx.lineWidth=1}
function drawAshenRuins(){ctx.fillStyle="#2d2624";ctx.fillRect(0,0,WORLD.w,WORLD.h);for(let i=0;i<25;i++){let x=100+i*71,y=180+(i*103)%780;ctx.fillStyle="#4a413e";ctx.fillRect(x,y,26,130);ctx.fillStyle="#66564d";ctx.fillRect(x-9,y-12,44,14)}for(let i=0;i<80;i++){ctx.fillStyle="#5a514d";ctx.fillRect((i*113)%1750,(i*71)%1080,3,3)}}
function drawObelisk(x,y){ctx.fillStyle="#6a6058";ctx.beginPath();ctx.moveTo(x-28,y+50);ctx.lineTo(x-12,y-100);ctx.lineTo(x+15,y-130);ctx.lineTo(x+31,y+50);ctx.closePath();ctx.fill();ctx.strokeStyle="#ba9562";ctx.stroke()}
function drawBelow(){ctx.fillStyle="#111019";ctx.fillRect(0,0,WORLD.w,WORLD.h);for(let i=0;i<100;i++){let x=(i*131)%1750,y=(i*73)%1100;ctx.fillStyle=i%4===0?"#4d3a5c":"#28253a";ctx.fillRect(x,y,2,2)}ctx.strokeStyle="#40374d";ctx.lineWidth=42;ctx.beginPath();ctx.moveTo(0,680);ctx.bezierCurveTo(450,620,620,730,900,590);ctx.bezierCurveTo(1180,450,1450,630,1800,500);ctx.stroke();ctx.lineWidth=1}}
function drawWorldObjects(){ctx.save();ctx.translate(-cam.x,-cam.y);const objs=getEntities();for(const o of objs){if(o.type==="npc")drawNpc(o);if(o.type==="enemy")drawEnemy(o);if(o.type==="portal")drawPortal(o);if(o.type==="loot")drawLoot(o);if(o.type==="landmark")drawLandmarkEntity(o);if(o.type==="exit")drawExit(o)}ctx.restore()}
function getEntities(){let a=[];if(S.player.area==="greywood"){a.push({id:"way",type:"landmark",x:930,y:405,name:"The Old Waystone"});a.push({id:"mara",type:"npc",x:520,y:440,name:"Mara"});a.push({id:"wolf",type:"enemy",x:1020,y:550,name:"Grey Wolf"});a.push({id:"cinder",type:"exit",x:245,y:505,name:"Cinder Road"});a.push({id:"salt",type:"exit",x:1490,y:760,name:"Saltmarsh"});a.push({id:"below",type:"portal",x:1240,y:330,name:"Sealed Hollow",hidden:!(S.player.level>=4&&S.quest.stage>=3)})}
else if(S.player.area==="cinder"){a.push({id:"mara",type:"npc",x:860,y:470,name:"Mara",memory:"contract"});a.push({id:"warden",type:"enemy",x:1180,y:540,name:"The Road Warden",boss:true});a.push({id:"bandit",type:"enemy",x:620,y:560,name:"Cinder Bandit"});a.push({id:"greywood",type:"exit",x:130,y:600,name:"Greywood"});a.push({id:"salt",type:"exit",x:1530,y:650,name:"Saltmarsh"})}
else if(S.player.area==="salt"){a.push({id:"shrine",type:"landmark",x:1080,y:410,name:"Drowned Shrine"});a.push({id:"bog",type:"enemy",x:910,y:570,name:"Bogling"});a.push({id:"greywood",type:"exit",x:1540,y:680,name:"Greywood"});a.push({id:"high",type:"portal",x:1450,y:300,name:"Mountain Gate",hidden:!(S.player.level>=5)})}
else if(S.player.area==="high"){a.push({id:"ashen",type:"exit",x:330,y:820,name:"Ashen Veil"});a.push({id:"greywood",type:"exit",x:1500,y:900,name:"Greywood"})}
else if(S.player.area==="ashen"){a.push({id:"below",type:"portal",x:1040,y:500,name:"The Door Below"});a.push({id:"high",type:"exit",x:1500,y:880,name:"Highreach"})}
else if(S.player.area==="below"){a.push({id:"void",type:"landmark",x:910,y:520,name:"Hollow Gate"});a.push({id:"high",type:"exit",x:1450,y:920,name:"A Stair Up"});a.push({id:"warden",type:"enemy",x:1180,y:500,name:"Something Wearing a Crown",boss:true})}return a.filter(o=>!o.hidden)}
function drawLabel(x,y,name,color="#e1e6ee"){ctx.font="10px Inter, sans-serif";ctx.textAlign="center";ctx.fillStyle="rgba(5,7,10,.82)";let tw=ctx.measureText(name).width+14;ctx.fillRect(x-tw/2,y,tw,20);ctx.strokeStyle="rgba(215,168,92,.32)";ctx.strokeRect(x-tw/2,y,tw,20);ctx.fillStyle=color;ctx.fillText(name,x,y+13)}
function drawNpc(o){ctx.fillStyle="#1b2530";ctx.beginPath();ctx.arc(o.x,o.y,24,0,7);ctx.fill();ctx.fillStyle="#c18b61";ctx.beginPath();ctx.arc(o.x,o.y-8,11,0,7);ctx.fill();ctx.fillStyle="#7b4f3b";ctx.fillRect(o.x-15,o.y+4,30,25);drawLabel(o.x,o.y+34,o.name,"#d8c49c")}
function drawEnemy(o){ctx.fillStyle=o.boss?"#5a2732":"#351820";ctx.beginPath();ctx.arc(o.x,o.y,30,0,7);ctx.fill();ctx.strokeStyle=o.boss?"#d26767":"#86404d";ctx.lineWidth=2;ctx.stroke();ctx.lineWidth=1;ctx.fillStyle="#df6e70";ctx.beginPath();ctx.arc(o.x-8,o.y-3,4,0,7);ctx.arc(o.x+8,o.y-3,4,0,7);ctx.fill();drawLabel(o.x,o.y+38,o.name,o.boss?"#ef9a86":"#d47c80")}
function drawPortal(o){ctx.strokeStyle="#8d7ab2";ctx.lineWidth=4;ctx.beginPath();ctx.arc(o.x,o.y,35,0,7);ctx.stroke();ctx.fillStyle="#211a30";ctx.beginPath();ctx.arc(o.x,o.y,28,0,7);ctx.fill();drawLabel(o.x,o.y+45,o.name,"#b7a1ff")}
function drawLoot(o){ctx.fillStyle="#e3bb67";ctx.save();ctx.translate(o.x,o.y);ctx.rotate(Math.PI/4);ctx.fillRect(-10,-10,20,20);ctx.restore();drawLabel(o.x,o.y+23,o.name,"#f0cb78")}
function drawLandmarkEntity(o){ctx.fillStyle="#6f604f";ctx.beginPath();ctx.moveTo(o.x-22,o.y+25);ctx.lineTo(o.x-16,o.y-22);ctx.lineTo(o.x,o.y-47);ctx.lineTo(o.x+16,o.y-22);ctx.lineTo(o.x+22,o.y+25);ctx.closePath();ctx.fill();ctx.strokeStyle="#c2a56e";ctx.stroke();drawLabel(o.x,o.y+35,o.name,"#d7bb80")}
function drawExit(o){ctx.fillStyle="#8a6641";ctx.fillRect(o.x-55,o.y-70,110,110);ctx.fillStyle="#b1834f";ctx.beginPath();ctx.moveTo(o.x-70,o.y-70);ctx.lineTo(o.x,o.y-125);ctx.lineTo(o.x+70,o.y-70);ctx.closePath();ctx.fill();ctx.fillStyle="#1b1410";ctx.fillRect(o.x-18,o.y-18,36,58);drawLabel(o.x,o.y+48,o.name,"#d5bb8c")}
function drawPlayer(){ctx.save();ctx.translate(S.player.x-cam.x,S.player.y-cam.y);ctx.fillStyle="#c9a264";ctx.globalAlpha=.34;ctx.beginPath();ctx.ellipse(0,27,32,10,0,0,7);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle="#dcc28a";ctx.beginPath();ctx.arc(0,-12,9,0,7);ctx.fill();ctx.fillStyle="#4a2d23";ctx.fillRect(-14,-3,28,28);ctx.fillStyle="#9d6d42";ctx.fillRect(-18,2,36,12);ctx.fillStyle="#e0c387";ctx.fillRect(-7,25,6,10);ctx.fillRect(2,25,6,10);ctx.restore()}
function drawAtmosphere(w,h){let grd=ctx.createRadialGradient(w*.5,h*.42,50,w*.5,h*.46,Math.max(w,h)*.74);grd.addColorStop(0,"rgba(255,212,144,.02)");grd.addColorStop(.65,"rgba(0,0,0,.08)");grd.addColorStop(1,"rgba(0,0,0,.62)");ctx.fillStyle=grd;ctx.fillRect(0,0,w,h);ctx.fillStyle="rgba(255,255,255,.018)";for(let i=0;i<160;i++){ctx.fillRect((i*83)%w,(i*47)%h,1,1)}}
function findNear(){nearEntity=null;if(combat||dialogue)return;let best=78;for(const o of getEntities()){let d=Math.hypot(o.x-S.player.x,o.y-S.player.y);if(d<best){best=d;nearEntity=o}}const p=document.getElementById("interactionPrompt");if(nearEntity){p.classList.remove("hidden");p.innerHTML="<b>E</b>  "+(nearEntity.type==="enemy"?"Engage ":nearEntity.type==="exit"?"Travel to ":nearEntity.type==="portal"?"Investigate ":"Interact with ")+nearEntity.name}else p.classList.add("hidden")}
function interact(){if(!nearEntity)return;let o=nearEntity;if(o.type==="enemy"){startCombat(o.id);return}if(o.type==="exit"){travel(o.id);return}if(o.id==="mara"){openMara();return}if(o.id==="way"){if(S.quest.stage===0){dialogueBox("The Old Waystone","The stone is warm. Your name is carved beneath a date that has not happened yet.",[[ "Touch it",()=>{S.quest.stage=1;S.quest.title="The Road Warden";S.quest.text="Mara on Cinder Road mentioned someone who knows why the waystone remembers you.";log("<b>STORY</b> The waystone knows your name.");closeDialogue()}],[ "Leave",closeDialogue]])}else toast("The stone has nothing new to say. Not yet.");return}
if(o.id==="shrine"){dialogueBox("Drowned Shrine","Something under the water knocks once against stone. Then twice.",[[ "Reach into the water",()=>{if(!S.player.inv.includes("coin"))S.player.inv.push("coin");log("<b>FOUND</b> Beggar's Coin. It is wet, but your hand is dry.");toast("Found: Beggar's Coin");closeDialogue();renderUI()}],[ "Walk away",closeDialogue]])}
if(o.type==="portal"){if(o.id==="below"){if(S.player.level>=4&&S.quest.stage>=1){S.player.flags.secret=true;travel("below");log("<b>SECRET DISCOVERY</b> You found a stair beneath the map.");evaluateClasses()}else toast("Something about this place is not ready for you.")}else if(o.id==="high"){travel("high")}}
}
function openMara(){dialogueBox("Mara, Contract Keeper","You are carrying yourself like someone who thinks the road is neutral. It isn't.",[[ "Ask for work",()=>dialogueBox("Mara, Contract Keeper","Take the Red Coin. Find the Road Warden. When he offers you a shortcut, refuse it. You will learn more from what he does next.",[[ "Take the Red Coin",()=>{S.player.flags.red=true;S.player.quest||null;log("Mara gave you the Red Coin.");toast("Quest item acquired");closeDialogue()}],[ "Leave",closeDialogue]])],[ "Ask her about the waystone",()=>dialogueBox("Mara","You have already seen it, haven't you?",[[ "Yes.",()=>{S.quest.stage=Math.max(S.quest.stage,1);closeDialogue()}],[ "No.",closeDialogue()]])]])}
function travel(id){if(id==="cinder"||id==="salt"||id==="high"||id==="ashen"||id==="below"||id==="greywood"){if(id==="high"&&S.player.level<5){toast("The mountain gate does not open for you.");return}if(!S.known.includes(id))S.known.push(id);S.player.area=id;S.player.x=DATA.areas[id]?.spawn?.[0]||700;S.player.y=DATA.areas[id]?.spawn?.[1]||520;log("<b>ARRIVED</b> "+DATA.areas[id].name+" — "+DATA.areas[id].sub);renderUI();save()}}
function startCombat(id){let base=DATA.enemies[id]||DATA.enemies.wolf;combat={e:structuredClone(base),guard:false,veil:false,focus:false};document.getElementById("combatHud").classList.remove("hidden");renderCombat();log("A "+base.name+" blocks your path.")}
function renderCombat(){if(!combat)return;let e=combat.e;document.getElementById("combatHud").innerHTML="<div class='combat-box'><div class='combat-sub'>ENCOUNTER</div><div class='combat-name'>"+e.name+"</div><div class='combat-sub'>LEVEL "+e.level+"</div><div class='bar' style='margin-top:13px'><i class='hp' style='width:"+(e.hp/(DATA.enemies[e.id]?.hp||e.hp)*100)+"%'></i></div><div class='combat-grid'><div class='combat-stat'><div class='combat-sub'>YOU</div><b>"+Math.round(S.player.hp)+" / "+S.player.maxHp+" HP</b><br><span class='muted'>"+Math.round(S.player.mp)+" / "+S.player.maxMp+" MP</span></div><div class='combat-stat'><div class='combat-sub'>ENEMY</div><b>"+e.hp+" / "+DATA.enemies[e.id].hp+" HP</b><br><span class='muted'>ARMOR "+e.armor+"</span></div></div><div class='combat-actions'><button class='primary' data-combat='strike'>STRIKE</button>"+S.player.skills.map(id=>skill(id)).filter(Boolean).map(s=>"<button data-combat='"+s.id+"'>"+s.name+" <small>"+s.cost+" MP</small></button>").join("")+"<button data-combat='flee'>FLEE</button></div></div>"}
function enemyTurn(){if(!combat)return;let e=combat.e;let dmg=Math.max(1,Math.round(e.power-armor()*.45+Math.random()*5));if(combat.guard){dmg=Math.max(1,Math.round(dmg*.4));combat.guard=false}if(combat.veil){dmg=0;combat.veil=false}S.player.hp=Math.max(0,S.player.hp-dmg);if(dmg)pop("-"+dmg,"bad");else pop("DODGE","good");if(S.player.hp<=0){fall();return}renderCore();renderCombat()}
function strike(){if(!combat)return;let isCrit=Math.random()*100<crit(),d=Math.max(1,Math.round(attackPower()*(isCrit?1.9:1)-combat.e.armor*.6));if(combat.focus)d=Math.round(d*1.2);combat.e.hp=Math.max(0,combat.e.hp-d);pop((isCrit?"CRIT ":"")+d,isCrit?"crit":"");if(combat.e.hp<=0){victory();return}enemyTurn()}
function combatSkill(id){if(!combat)return;let s=skill(id);if(!s)return;if(s.cost>S.player.mp){toast("Not enough MP");return}if(id==="strike"){strike();return}S.player.mp-=s.cost;if(id==="guard"){combat.guard=true;pop("GUARD","good")}if(id==="focus"){combat.focus=true;S.player.mp=Math.min(S.player.maxMp,S.player.mp+Math.round(S.player.maxMp*.25));pop("FOCUS","good")}if(id==="ember"){let d=Math.max(2,Math.round(S.player.int*2.2+magic()*2.4+8));combat.e.hp=Math.max(0,combat.e.hp-d);pop("EMBER "+d,"crit")}if(id==="bloodstep"){S.player.hp=Math.max(1,S.player.hp-10);let d=Math.round(attackPower()*2.3);combat.e.hp=Math.max(0,combat.e.hp-d);pop("BLOOD "+d,"crit")}if(id==="veil"){combat.veil=true;pop("VEIL","good")}if(combat.e.hp<=0){victory();return}enemyTurn()}
function victory(){let e=combat.e;S.player.gold+=e.gold;addXP(e.xp);S.dead.push(e.id);if(e.id==="warden"){S.player.flags.firstBoss=true;S.quest.stage=2;S.quest.title="A Name in the Dark";S.quest.text="Return to Greywood. The mark on the waystone was yours — but not from this life."}if(e.loot&&!S.player.inv.includes(e.loot)&&Math.random()>.35){S.player.inv.push(e.loot);let i=item(e.loot);log("<b>LOOT FOUND</b> "+i.name+" ["+i.rarity.toUpperCase()+"]");toast("Loot: "+i.name)}combat=null;document.getElementById("combatHud").classList.add("hidden");renderUI();save()}
function fall(){S.player.hp=Math.max(1,Math.floor(S.player.maxHp*.2));S.player.area="greywood";S.player.x=700;S.player.y=520;combat=null;document.getElementById("combatHud").classList.add("hidden");log("<b>YOU FELL</b> The road remembers. You wake beneath Greywood rain.");renderUI()}
function dialogueBox(speaker,text,choices){dialogue=true;document.getElementById("dialogueSpeaker").textContent=speaker;document.getElementById("dialogueText").textContent=text;document.getElementById("dialogueChoices").innerHTML=choices.map((x,i)=>"<button class='choice' data-choice='"+i+"'>"+x[0]+"</button>").join("");window.__choices=choices;document.getElementById("dialogue").classList.remove("hidden")}
function closeDialogue(){dialogue=false;document.getElementById("dialogue").classList.add("hidden")}
function renderCore(){let p=S.player,c=cls(p.classId);document.getElementById("playerName").textContent=p.name;document.getElementById("levelText").textContent=p.level;document.getElementById("className").textContent=c.name;document.getElementById("classRarity").textContent=c.rarity.toUpperCase();document.getElementById("classRarity").className="rarity "+c.rarity;document.getElementById("hpText").textContent=Math.round(p.hp)+" / "+p.maxHp;document.getElementById("mpText").textContent=Math.round(p.mp)+" / "+p.maxMp;document.getElementById("xpText").textContent=Math.round(p.xp)+" / "+xpNeed()+" XP";document.getElementById("hpBar").style.width=(p.hp/p.maxHp*100)+"%";document.getElementById("mpBar").style.width=(p.mp/p.maxMp*100)+"%";document.getElementById("xpBar").style.width=(p.xp/xpNeed()*100)+"%";document.getElementById("questTitle").textContent=S.quest.title;document.getElementById("questText").textContent=S.quest.text;document.getElementById("locationName").textContent=DATA.areas[p.area].name.toUpperCase();document.getElementById("zoneBadge").textContent=DATA.areas[p.area].name.toUpperCase();document.getElementById("nearby").innerHTML=getEntities().slice(0,6).map(o=>"<div class='near-row'><span>"+o.name+"</span><span class='near-type'>"+o.type.toUpperCase()+"</span></div>").join("");document.getElementById("worldLog").innerHTML=S.log.slice(0,10).map(x=>"<div class='log-entry'>"+x+"</div>").join("")}
function renderUI(){renderCore();draw()}
function openPanel(which){document.getElementById("panelShade").classList.remove("hidden");document.getElementById("panel").classList.remove("hidden");if(which==="character")characterPanel();if(which==="inventory")inventoryPanel();if(which==="map")mapPanel();if(which==="skills")skillsPanel();if(which==="codex")codexPanel()}
function closePanel(){document.getElementById("panelShade").classList.add("hidden");document.getElementById("panel").classList.add("hidden")}
function characterPanel(){let p=S.player,c=cls(p.classId);document.getElementById("panelKicker").textContent="CHARACTER";document.getElementById("panelTitle").textContent=p.name;document.getElementById("panelBody").innerHTML="<div class='info-box'><div class='section-title'>CORE</div>"+[["Level",p.level],["Class",c.name+" • "+c.rarity],["HP",Math.round(p.hp)+" / "+p.maxHp],["MP",Math.round(p.mp)+" / "+p.maxMp],["Gold",p.gold],["Attack",Math.round(attackPower())],["Armor",Math.round(armor())],["Crit",crit()+"%"],["Magic",Math.round(magic())]].map(r=>"<div class='info-row'><span>"+r[0]+"</span><span class='value'>"+r[1]+"</span></div>").join("")+"</div><div class='section-title'>ATTRIBUTES</div><div class='grid-2'>"+[["STR",p.str],["DEX",p.dex],["INT",p.int],["VIT",p.vit],["LUCK",p.luck]].map(r=>"<div class='info-box info-row'><span>"+r[0]+"</span><span class='value'>"+r[1]+"</span></div>").join("")+"</div><div class='section-title'>CURRENT CLASS</div><div class='lore-card'><b>"+c.name+"</b><p>"+c.desc+"</p><div class='lock'>"+c.req+"</div></div>"}
function inventoryPanel(){document.getElementById("panelKicker").textContent="INVENTORY";document.getElementById("panelTitle").textContent="Pack & Equipment";document.getElementById("panelBody").innerHTML="<div class='section-title'>ITEMS • "+S.player.inv.length+"</div>"+S.player.inv.map(id=>{let i=item(id),eq=Object.values(S.player.eq).includes(id);return"<div class='item-card'><div><strong>"+i.name+"</strong><small>"+i.rarity.toUpperCase()+" • "+i.type+"<br>"+i.desc+"</small></div><button class='equip' data-equip='"+id+"'>"+(eq?"EQUIPPED":"EQUIP")+"</button></div>"}).join("")+"<div class='section-title'>EQUIPPED</div>"+Object.entries(S.player.eq).map(r=>"<div class='info-row'><span>"+r[0].toUpperCase()+"</span><span class='value'>"+(r[1]?item(r[1]).name:"Empty")+"</span></div>").join("")}
function skillPanel(){skillsPanel()}
function skillsPanel(){document.getElementById("panelKicker").textContent="SKILLS";document.getElementById("panelTitle").textContent="Known Skills";document.getElementById("panelBody").innerHTML="<div class='section-title'>DISCOVERED</div>"+S.player.skills.map(id=>{let s=skill(id);return"<div class='skill-card'><b>"+s.name+"</b><span>"+s.kind+" • "+s.cost+" MP</span><p>"+s.desc+"</p></div>"}).join("")+"<div class='section-title'>LOCKED KNOWLEDGE</div>"+DATA.skills.filter(s=>!S.player.skills.includes(s.id)).map(s=>"<div class='skill-card'><b>???</b><span>LEVEL "+s.lvl+"</span><p>Something has not taught you this yet.</p><div class='lock'>DISCOVERY CONDITION UNKNOWN</div></div>").join("")}
function mapPanel(){document.getElementById("panelKicker").textContent="WORLD";document.getElementById("panelTitle").textContent="The Known World";document.getElementById("panelBody").innerHTML="<div class='map-frame'><div class='map-river'></div>"+Object.entries(DATA.areas).map(([id,a])=>{let coords={greywood:[49,55],cinder:[22,37],salt:[76,68],high:[82,23],ashen:[46,16],below:[66,45]}[id],known=S.known.includes(id);return"<button class='map-point "+(!known?"locked ":"")+(id==="below"?"secret":"")+"' style='left:"+coords[0]+"%;top:"+coords[1]+"%' data-map='"+id+"'><span>"+(known?a.name:"???")+"</span></button>"}).join("")+"</div><p class='muted'>The map records places before it explains them. Some places will remain blank until the world decides you are ready.</p>"}
function codexPanel(){document.getElementById("panelKicker").textContent="CODEX";document.getElementById("panelTitle").textContent="Things You Know";document.getElementById("panelBody").innerHTML="<div class='section-title'>CLASSES</div>"+DATA.classes.map(c=>"<div class='lore-card'><b>"+(c.id===S.player.classId?c.name:"???")+"</b><p>"+(c.id===S.player.classId?c.desc:"An undiscovered class exists here.")+"</p></div>").join("")+"<div class='section-title'>THE WAYSTONE</div><div class='lore-card'><b>A familiar mark</b><p>Your handwriting is carved beneath a date you do not remember living through.</p></div>"}
document.addEventListener("click",e=>{let b=e.target.closest("[data-panel]");if(b){openPanel(b.dataset.panel);return}if(e.target.closest("#closePanel")||e.target.closest("#panelShade")){closePanel();return}b=e.target.closest("[data-choice]");if(b){window.__choices[+b.dataset.choice][1]();return}b=e.target.closest("[data-combat]");if(b){let id=b.dataset.combat;if(id==="flee")fall();else combatSkill(id);renderCombat();return}b=e.target.closest("[data-equip]");if(b){let i=item(b.dataset.equip);S.player.eq[i.slot]=i.id;log("<b>EQUIPPED</b> "+i.name);inventoryPanel();renderCore();save();return}b=e.target.closest("[data-map]");if(b){let id=b.dataset.map;if(S.known.includes(id)||DATA.areas[id].open)travel(id);else toast("You have not discovered a way there yet.");return}});
document.addEventListener("keydown",e=>{keys[e.key.toLowerCase()]=true;if(e.code==="Space"){e.preventDefault();if(combat)strike()}if(e.key.toLowerCase()==="e")interact();if(e.key==="Escape"){closePanel();if(dialogue)closeDialogue()}if(e.key.toLowerCase()==="c")openPanel("character");if(e.key.toLowerCase()==="i")openPanel("inventory");if(e.key.toLowerCase()==="m")openPanel("map");if(e.key.toLowerCase()==="k")openPanel("skills");if(e.key.toLowerCase()==="j")openPanel("codex");if(e.key.toLowerCase()==="q"&&!combat)document.getElementById("healBtn").click();if(e.key==="Shift"&&combat){if(!combat)return;combat.veil=true;S.player.mp=Math.min(S.player.maxMp,S.player.mp+3);enemyTurn()}});
document.addEventListener("keyup",e=>keys[e.key.toLowerCase()]=false);
document.getElementById("attackBtn").onclick=()=>combat?strike():toast("Nothing is attacking you. Yet.");
document.getElementById("dodgeBtn").onclick=()=>{if(combat){combat.veil=true;S.player.mp=Math.min(S.player.maxMp,S.player.mp+3);enemyTurn()}else toast("You slip into the brush.")};
document.getElementById("healBtn").onclick=()=>{if(S.player.gold<5){toast("You need 5 gold.");return}S.player.gold-=5;S.player.hp=Math.min(S.player.maxHp,S.player.hp+35);pop("+35 HP","good");renderUI();save()};
document.getElementById("trackQuest").onclick=()=>toast("Thread tracked: "+S.quest.title);
let last=performance.now();function loop(t){let dt=Math.min(.04,(t-last)/1000);last=t;movement(dt);draw();requestAnimationFrame(loop)}
seedWorld();setTimeout(()=>document.getElementById("boot").classList.add("hide"),900);renderUI();requestAnimationFrame(loop);
